---
- name: Deploy Docker image on EC2 instance
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present
      tags: docker

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      tags: docker

    - name: Run Docker container
      docker_container:
        name: express-demo-app
        image: elyesbelgouthi/express-demo-app:latest
        state: started
        restart_policy: always
      tags: docker
